[package]
name = "fruits_ecs_world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
fruits_ecs_data = { path = "../fruits_ecs_data" }
fruits_ecs_schedule = { path = "../fruits_ecs_schedule" }
