[package]
name = "fruits_ecs_component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
fruits_ecs_data_usage = { path = "../fruits_ecs_data_usage" }
fruits_utils = { path = "../fruits_utils" }