[package]
name = "fruits_window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
pollster = "0.3"
winit = "0.30.4"
wgpu = "22.0.0"
